### ISSUE TITLE
Unable to prepare setup for platform zoned_heating.switch: Platform not found

### ISSUE THREAD

**Issue by msolomos** [nielsfaber/zoned-heating#13]
hello,
after update to 2023.7.2 I get the following error

`Unable to prepare setup for platform zoned_heating.switch: Platform not found (cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)).`

Any chance to update code again so it worked??

**Comment by msolomos** [comment]
Anyone please?  
I have several TRV's and zone-heating is an integration I use very much.

**Comment by nielsfaber** [comment]
I created version v1.0.1 which should fix this.
Please update and check if the issue is solved for you.
You can close this issue if this is the case.

**Comment by msolomos** [comment]
I've updated my version and the error got disappeared. 

However when I try to setup up again running the wizard, I go through the steps, got msg that setup was succesful but no entry is created.
Help me pls! I need zone heating to work for my newborn son

**Comment by msolomos** [comment]
> I created version v1.0.1 which should fix this. Please update and check if the issue is solved for you. You can close this issue if this is the case.

Would you please get back to me about this matter? I love this project and I want it to work again.
I have sent you some messages but I still haven't get a reply

**Comment by nielsfaber** [comment]
I just have returned from holidays, so I haven't been able to investigate this.
I will take a look at the problem when I have the time (hopefully somewhere this week) and let you know if I find something.
It would be helpful if you can share some details of the issue you are running into.
So, which step is failing and which error message appears? Do you also see an error in the HA logs?

**Comment by msolomos** [comment]
thank you for your reply. 
So it doesn't fail in any step. 
It completes setup and it gives a confirmation message. 
But it doesn't create any zone heating entities!  And nothing is recorded to the logs file!
it's pretty strange!  I have recorded screen for your information. Hope it helps
https://www.dropbox.com/scl/fi/b2m7uooelehx6oaxy9tdk/www_screencapture_com_2023-9-17_21_44.webm?rlkey=w4u0nnb6faf7eji5rd75gl3t8&dl=0

Awaiting the pleasure of your reply

**Comment by nielsfaber** [comment]
I looked into this, and indeed I don't see 'no devices or entities' displayed under the integration page in HA.
However, the entity switch.zoned_heating is in fact created and it also performs its function as normal.
So I think the issue is just a visualisation issue.
I don't know what causes this, it seems related to a recent change in HA.
I suggest you to try turning on the heater of a zone, you should see the integration works OK.

**Comment by msolomos** [comment]
I confirm that the issue is a visualisation issue. Switch.zoned_heating is working properly and performs its function as normal.
But is there any chance you can correct this error?

![image](https://github.com/nielsfaber/zoned-heating/assets/72358278/274137a8-e163-40f7-801e-7ea20a72c8ab)

Am using in total 13 TRV's at two floors and I can't even think what I would do without this integration!
